### ISSUE TITLE
Fails to build on `x86_64-unknown-netbsd`

### ISSUE THREAD

**Issue by lnicola** [notify-rs/notify#344]
```
$ git checkout 5.0.0-pre.11
Previous HEAD position was 43ea645 Add missing comma in "As used by:" list
HEAD is now at 71c57b4 Prepare 5.0.0-pre.11
$ cargo build --target x86_64-unknown-netbsd
Updating crates.io index
   Compiling kqueue-sys v1.0.2
error[E0308]: mismatched types
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/kqueue-sys-1.0.2/src/lib.rs:68:20
   |
68 |             udata: ptr::null_mut(),
   |                    ^^^^^^^^^^^^^^^ expected `isize`, found *-ptr
   |
   = note:     expected type `isize`
           found raw pointer `*mut _`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `kqueue-sys`

To learn more, run the command again with --verbose.
```

Spotted in https://github.com/rust-lang/rust/pull/87719#issuecomment-891625996.

**Comment by 0xpr03** [comment]
@xanderio can you have a look at this ?

**Comment by lnicola** [comment]
Looks like it's a kqueue-sys bug.

**Comment by 0xpr03** [comment]
This was probably introduced by #335 though it seems to stem from upstream. I sadly can't test this.

**Comment by lnicola** [comment]
Filed https://gitlab.com/worr/rust-kqueue-sys/-/issues/1.

**Comment by 0xpr03** [comment]
I've added a PR to pin the 1.0.3 as minimum, what I'm currently missing is a way to run this on github actions a test build.

**Comment by 0xpr03** [comment]
Released as 5.0.0-pre.12
